[tools]
helix = "latest"
ripgrep = "latest"
gh = "latest"
go = "latest"
# skopeo = "latest"  # See issue #7 for adding skopeo support

[env]
# Environment variables can be defined here if needed

[alias]
# Tool aliases can be defined here if needed
