[tools]
helix = "latest"
ripgrep = "latest"
gh = "latest"
go = "latest"
pre-commit = "latest"
starship = "latest"
direnv = "latest"
"go:golang.org/x/tools/gopls" = "latest"
editorconfig-checker = "latest"
# skopeo = "latest"  # See issue #7 for adding skopeo support

[env]
# Environment variables can be defined here if needed

[settings]
activate_aggressive = true
experimental = true

[alias]
# Tool aliases can be defined here if needed

[tasks.lint]
description = "Run editorconfig linting"
run = "editorconfig-checker"
