#!/usr/bin/env bash

export DOT_SOURCE=$HOME/.dot
source $DOT_SOURCE/varz.sh
source $DOT_SOURCE/env/activate
source $DOT_SOURCE/alias/activate

case $- in
    *i*) ;;
      *) return;;
esac

source $DOT_SOURCE/term/activate
source $DOT_SOURCE/reminders

# Source secret things (maybe aws creds. maybe not. who's to know)
if [[ -f $HOME/.secret ]]; then
    source $HOME/.secret
fi

#export PATH=$(dedupe_path)
mise=$(command -v mise)
if [[ ! -z $mise ]]; then
    eval "$(mise activate bash)"
fi
