#!/usr/bin/env bash

export DOT_SOURCE=$HOME/.dot
source $DOT_SOURCE/varz.sh
source $DOT_SOURCE/env/activate
source $DOT_SOURCE/alias/activate

case $- in
    *i*) ;;
      *) return;;
esac

source $DOT_SOURCE/term/activate

# Source secret things (maybe aws creds. maybe not. who's to know)
if [[ -f $HOME/.secret ]]; then
    source $HOME/.secret
fi

#export PATH=$(dedupe_path)
if command -v mise >/dev/null 2>&1; then
    eval "$(mise activate bash)"
fi
