#!/bin/sh

# pets: destfile=/usr/local/bin/gitea, owner=git, group=git, mode=0774
# pets: post=usermod -s /usr/local/bin/gitea git

ssh -p 2222 -o StrictHostKeyChecking=no git@127.0.0.1 "SSH_ORIGINAL_COMMAND=\"$SSH_ORIGINAL_COMMAND\" $0 $@"

